# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medico.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests

ngrok = 'http://f7d4-170-0-71-179.ngrok.io'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Médico")
        MainWindow.resize(593, 395)
        MainWindow.setStyleSheet("background-color: rgb(255, 24, 55);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(250, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setStyleSheet("color: rgb(0,0,0);")
        self.label_titulo.setObjectName("label_titulo")
        self.listWidget_pacientes = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_pacientes.setGeometry(QtCore.QRect(10, 40, 201, 331))
        self.listWidget_pacientes.setObjectName("listWidget_pacientes")
        self.label_temperatura = QtWidgets.QLabel(self.centralwidget)
        self.label_temperatura.setGeometry(QtCore.QRect(250, 70, 121, 91))
        self.label_temperatura.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "background-color: rgb(0, 0, 127);")
        self.label_temperatura.setText("")
        self.label_temperatura.setObjectName("label_temperatura")
        self.label_frequencia = QtWidgets.QLabel(self.centralwidget)
        self.label_frequencia.setGeometry(QtCore.QRect(250, 200, 121, 91))
        self.label_frequencia.setStyleSheet("color: rgb(255, 255, 255);\n"
                                            "background-color: rgb(0, 0, 127);")
        self.label_frequencia.setText("")
        self.label_frequencia.setObjectName("label_frequencia")
        self.label_pressao = QtWidgets.QLabel(self.centralwidget)
        self.label_pressao.setGeometry(QtCore.QRect(430, 70, 121, 91))
        self.label_pressao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(0, 0, 127);")
        self.label_pressao.setText("")
        self.label_pressao.setObjectName("label_pressao")
        self.label_saturacao = QtWidgets.QLabel(self.centralwidget)
        self.label_saturacao.setGeometry(QtCore.QRect(430, 200, 121, 91))
        self.label_saturacao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(0, 0, 127);")
        self.label_saturacao.setText("")
        self.label_saturacao.setObjectName("label_saturacao")
        self.label_titulo_temperatura = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_temperatura.setGeometry(
            QtCore.QRect(270, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_temperatura.setFont(font)
        self.label_titulo_temperatura.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                    "background-color: rgb(0, 0, 127);")
        self.label_titulo_temperatura.setObjectName("label_titulo_temperatura")
        self.label_titulo_pressao = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_pressao.setGeometry(QtCore.QRect(470, 70, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_pressao.setFont(font)
        self.label_titulo_pressao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                "background-color: rgb(0, 0, 127);")
        self.label_titulo_pressao.setObjectName("label_titulo_pressao")
        self.label_titulo_freq = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_freq.setGeometry(QtCore.QRect(280, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_freq.setFont(font)
        self.label_titulo_freq.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "background-color: rgb(0, 0, 127);")
        self.label_titulo_freq.setObjectName("label_titulo_freq")
        self.label_titulo_saturacao = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_saturacao.setGeometry(QtCore.QRect(460, 200, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_saturacao.setFont(font)
        self.label_titulo_saturacao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "background-color: rgb(0, 0, 127);")
        self.label_titulo_saturacao.setObjectName("label_titulo_saturacao")
        self.label_titulo_temperatura_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_temperatura_2.setGeometry(
            QtCore.QRect(250, 320, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_temperatura_2.setFont(font)
        self.label_titulo_temperatura_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                      "background-color: rgb(0, 0, 127);")
        self.label_titulo_temperatura_2.setObjectName(
            "label_titulo_temperatura_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 320, 41, 16))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                    "color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.listWidget_pacientes.itemClicked.connect(self.listwidgetclicked)

    def listwidgetclicked(self, item):
        index = self.listWidget_pacientes.row(item)
        self.label_frequencia.setText(str(self.rq[index]['freq']))
        self.label_pressao.setText(str(self.rq[index]['pressao1']) + 'x' + str(self.rq[index]['pressao2']))
        self.label_saturacao.setText(str(self.rq[index]['resp']))
        self.label_temperatura.setText(str(self.rq[index]['temp']))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Connect Covid"))
        __sortingEnabled = self.listWidget_pacientes.isSortingEnabled()
        self.listWidget_pacientes.setSortingEnabled(False)
        self.listWidget_pacientes.setSortingEnabled(__sortingEnabled)
        self.label_titulo_temperatura.setText(
            _translate("MainWindow", "Temperatura"))
        self.label_titulo_pressao.setText(_translate("MainWindow", "Pressão"))
        self.label_titulo_freq.setText(_translate("MainWindow", "Frequencia"))
        self.label_titulo_saturacao.setText(
            _translate("MainWindow", "Saturação"))
        self.label_titulo_temperatura_2.setText(
            _translate("MainWindow", "Situação"))
        for p in range(len(self.rq)):
            item = QtWidgets.QListWidgetItem()
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.NoBrush)
            item.setBackground(brush)
            brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
            brush.setStyle(QtCore.Qt.NoBrush)
            item.setForeground(brush)
            item.setText(_translate("MainWindow", self.rq[p]['nome']))
            self.listWidget_pacientes.addItem(item)
                   
    def listar_pacientes(self):
        self.rq = requests.get(url=f'{ngrok}/patients').json()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.listar_pacientes()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
