# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medico.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import time

ngrok = 'http://127.0.0.1:5000/'

class Ui_MainWindow(QtCore.QObject):
    addRequested = QtCore.pyqtSignal(str)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 395)
        MainWindow.setStyleSheet("\n"
                                 "background-color: rgb(255, 24, 93);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(250, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setStyleSheet("color: rgb(0,0,0);")
        self.label_titulo.setObjectName("label_titulo")
        self.listWidget_pacientes = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_pacientes.setGeometry(QtCore.QRect(10, 70, 201, 291))
        self.listWidget_pacientes.setObjectName("listWidget_pacientes")
        self.label_temperatura = QtWidgets.QLabel(self.centralwidget)
        self.label_temperatura.setGeometry(QtCore.QRect(250, 70, 121, 91))
        self.label_temperatura.setMouseTracking(False)
        self.label_temperatura.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "background-color: rgb(0, 0, 127);")
        self.label_temperatura.setText("")
        self.label_temperatura.setObjectName("label_temperatura")
        self.label_frequencia = QtWidgets.QLabel(self.centralwidget)
        self.label_frequencia.setGeometry(QtCore.QRect(250, 200, 121, 91))
        self.label_frequencia.setStyleSheet("color: rgb(255, 255, 255);\n"
                                            "background-color: rgb(0, 0, 127);")
        self.label_frequencia.setText("")
        self.label_frequencia.setObjectName("label_frequencia")
        self.label_pressao = QtWidgets.QLabel(self.centralwidget)
        self.label_pressao.setGeometry(QtCore.QRect(430, 70, 121, 91))
        self.label_pressao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(0, 0, 127);")
        self.label_pressao.setText("")
        self.label_pressao.setObjectName("label_pressao")
        self.label_saturacao = QtWidgets.QLabel(self.centralwidget)
        self.label_saturacao.setGeometry(QtCore.QRect(430, 200, 121, 91))
        self.label_saturacao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(0, 0, 127);")
        self.label_saturacao.setText("")
        self.label_saturacao.setObjectName("label_saturacao")
        self.label_titulo_temperatura = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_temperatura.setGeometry(
            QtCore.QRect(270, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_temperatura.setFont(font)
        self.label_titulo_temperatura.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                    "background-color: rgb(0, 0, 127);")
        self.label_titulo_temperatura.setObjectName("label_titulo_temperatura")
        self.label_titulo_pressao = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_pressao.setGeometry(QtCore.QRect(470, 70, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_pressao.setFont(font)
        self.label_titulo_pressao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                "background-color: rgb(0, 0, 127);")
        self.label_titulo_pressao.setObjectName("label_titulo_pressao")
        self.label_titulo_freq = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_freq.setGeometry(QtCore.QRect(280, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_freq.setFont(font)
        self.label_titulo_freq.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "background-color: rgb(0, 0, 127);")
        self.label_titulo_freq.setObjectName("label_titulo_freq")
        self.label_titulo_saturacao = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_saturacao.setGeometry(QtCore.QRect(460, 200, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_saturacao.setFont(font)
        self.label_titulo_saturacao.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "background-color: rgb(0, 0, 127);")
        self.label_titulo_saturacao.setObjectName("label_titulo_saturacao")
        self.label_titulo_temperatura_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_temperatura_2.setGeometry(
            QtCore.QRect(250, 320, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_temperatura_2.setFont(font)
        self.label_titulo_temperatura_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                      "background-color: rgb(0, 0, 127);")
        self.label_titulo_temperatura_2.setObjectName(
            "label_titulo_temperatura_2")
        self.label_titulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo_2.setGeometry(QtCore.QRect(20, 20, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_2.setFont(font)
        self.label_titulo_2.setStyleSheet("color: rgb(0,0,0);")
        self.label_titulo_2.setObjectName("label_titulo_2")
        self.botaoEstavel = QtWidgets.QPushButton(self.centralwidget)
        self.botaoEstavel.setGeometry(QtCore.QRect(330, 320, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.botaoEstavel.setFont(font)
        self.botaoEstavel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(0, 0, 127);")
        self.botaoEstavel.setObjectName("botaoEstavel")
        self.botaoEmergencia = QtWidgets.QPushButton(self.centralwidget)
        self.botaoEmergencia.setGeometry(QtCore.QRect(410, 320, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.botaoEmergencia.setFont(font)
        self.botaoEmergencia.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(0, 0, 127);")
        self.botaoEmergencia.setObjectName("botaoEmergencia")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.addRequested.connect(self.listWidget_pacientes.addItem)
        self.listWidget_pacientes.itemClicked.connect(self.listwidgetclicked)
        self.botaoEmergencia.clicked.connect(self.alertaEmergencia)
        self.botaoEstavel.clicked.connect(self.estavel)
        

    def listwidgetclicked(self, item):
       index = self.listWidget_pacientes.row(item)
       self.label_frequencia.setText(str(self.rq[index]['freq']))
       self.label_pressao.setText(str(self.rq[index]['pressao1']) + 'x' + str(self.rq[index]['pressao2']))
       self.label_saturacao.setText(str(self.rq[index]['resp']))
       self.label_temperatura.setText(str(self.rq[index]['temp']))
       self.id = self.rq[index]['cpf']
       print(self.id)

    def sendAlert(self, alert) -> dict:
        return {
            'status': alert,
        }
    
    def estavel(self):
        r = requests.put(
            url=f'{ngrok}/patient/alert/{int(self.id)}', json=self.sendAlert('Estável'))
    
    def alertaEmergencia(self):
        r = requests.put(
            url=f'{ngrok}/patient/alert/{int(self.id)}', json=self.sendAlert('Emergência'))        



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Connect Covid"))
        self.label_titulo_temperatura.setText(
            _translate("MainWindow", "Temperatura"))
        self.label_titulo_pressao.setText(_translate("MainWindow", "Pressão"))
        self.label_titulo_freq.setText(_translate("MainWindow", "Frequencia"))
        self.label_titulo_saturacao.setText(
            _translate("MainWindow", "Saturação"))
        self.label_titulo_temperatura_2.setText(
            _translate("MainWindow", "Situação:"))
        self.label_titulo_2.setText(_translate(
            "MainWindow", "Prioridade de atendimento"))
        self.botaoEstavel.setText(_translate("MainWindow", "Estável"))
        self.botaoEmergencia.setText(_translate("MainWindow", "Emergência"))
        self.thread_start = MyThread()
        self.thread_start.ard_signal.connect(self.update)        
        self.thread_start.start()

    def listar_pacientes(self) -> dict:
        self.rq = requests.get(url=f'{ngrok}/patients').json()
        return self.rq

    def update(self, signal):
        _translate = QtCore.QCoreApplication.translate
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setText(_translate("MainWindow", signal))
        self.listWidget_pacientes.addItem(item)


class MyThread(QtCore.QThread):
    ard_signal = QtCore.pyqtSignal(str)
    
    def __init__(self):
        QtCore.QThread.__init__(self)
        
    def run(self):
        while 1:
            ui.listWidget_pacientes.clear()
            resp = ui.listar_pacientes()
            time.sleep(3)
            for p in range(len(resp)):
                self.ard_signal.emit(resp[p]['nome'])

# def process_signal(result):
#     print(result)
#     sys.exit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


